// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0PwDLMZ4liGZLQOcO31IAFbc2DubXPns',
    appId: '1:130725020117:android:781a6218e6c7123479fd5c',
    messagingSenderId: '130725020117',
    projectId: 'ordrz-app',
    databaseURL: 'https://ordrz-app-default-rtdb.firebaseio.com',
    storageBucket: 'ordrz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZ-sQ_orSOKMA6dreB0b4HVkUb76yE38',
    appId: '1:130725020117:ios:15b048db420efd4c79fd5c',
    messagingSenderId: '130725020117',
    projectId: 'ordrz-app',
    databaseURL: 'https://ordrz-app-default-rtdb.firebaseio.com',
    storageBucket: 'ordrz-app.appspot.com',
    androidClientId: '130725020117-hdjh0ngcqi009ga03l2mvu5ldgnoaet3.apps.googleusercontent.com',
    iosClientId: '130725020117-li166bh3svqd0g8fnsmtviv6u8dh3mu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantUserAdmin',
  );
}
